DO $$
BEGIN
  IF NOT (true = true OR false = true) THEN RAISE EXCEPTION '1'; END IF;
  IF NOT (false = false OR false = true) THEN RAISE EXCEPTION '2'; END IF;
  IF NOT (5 BETWEEN 1 AND 10) THEN RAISE EXCEPTION '3'; END IF;
  IF NOT (10485760 BETWEEN 1 AND 20971520) THEN RAISE EXCEPTION '4'; END IF;
  IF NOT (31457280 BETWEEN 1 AND 52428800) THEN RAISE EXCEPTION '5'; END IF;
  IF NOT (ARRAY['image', 'document']::text[] <@ ARRAY['image', 'document']::text[]) THEN RAISE EXCEPTION '6'; END IF;
END $$;
